export default {
  tutorialSidebar: [
    'the-nature-and-nurture-of-cooperation-and-competition',
    {
      type: 'category',
      label: 'Core Argument',
      collapsed: false,
      items: [
        'nature-nurture-human-behavior',
        {
          type: 'category',
          label: 'Cooperation in Perspective',
          link: { type: 'doc', id: 'cooperation-in-perspective/cooperation-in-perspective' },
          collapsed: false,
          items: [
            'cooperation-in-perspective/what-is-cooperation/what-is-cooperation',
            'cooperation-in-perspective/what-is-adversarial-behavior/what-is-adversarial-behavior',
            'cooperation-in-perspective/history-of-human-cooperation-and-competition/history-of-human-cooperation-and-competition',
          ],
        },
        'evolved-cooperation/evolved-cooperation',
        'learned-cooperation/learned-cooperation',
        'learning-selection-interaction/interaction-evolved-learned-cooperation/interaction-evolved-learned-cooperation',
        'learning-selection-interaction/interaction-evolved-learned-cooperation/foundational-theory/baldwin-effect',
      ],
    },
    'evidence-so-far',
    {
      type: 'category',
      label: 'Model Library',
      link: { type: 'doc', id: 'model-library' },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Evolved Cooperation Models',
          collapsed: false,
          items: [
            { type: 'autogenerated', dirName: 'evolved-cooperation' },
          ],
        },
        {
          type: 'category',
          label: 'Learned Cooperation Models',
          collapsed: false,
          items: [
            {
              type: 'category',
              label: "Prisoner's Dilemma",
              link: { type: 'doc', id: 'learned-cooperation/prisoners-dilemma/prisoners-dilemma' },
              collapsed: false,
              items: [],
            },
            {
              type: 'category',
              label: "Repeated Prisoner's Dilemma",
              link: { type: 'doc', id: 'learned-cooperation/repeated-prisoners-dilemma/repeated-prisoners-dilemma' },
              collapsed: false,
              items: [
                'learned-cooperation/repeated-prisoners-dilemma/ppo-study',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Learning × Selection Interaction Models',
          collapsed: false,
          items: [
            {
              type: 'category',
              label: 'PredPreyGrass',
              link: { type: 'generated-index' },
              collapsed: true,
              items: [
                'learning-selection-interaction/interaction-evolved-learned-cooperation/predpreygrass/predpreygrass',
                'learning-selection-interaction/interaction-evolved-learned-cooperation/predpreygrass/predpreygrass-energy-entropy',
                'learning-selection-interaction/interaction-evolved-learned-cooperation/predpreygrass/evolution-boundary-predpreygrass',
                'learning-selection-interaction/interaction-evolved-learned-cooperation/predpreygrass/marl-challenges-predpreygrass',
              ],
            },
            {
              type: 'category',
              label: 'Two-Timescale Simulations',
              link: { type: 'doc', id: 'learning-selection-interaction/interaction-evolved-learned-cooperation/two-timescale-simulations/simulations-index' },
              collapsed: true,
              items: [
                'learning-selection-interaction/interaction-evolved-learned-cooperation/two-timescale-simulations/simulations-model-1-trust-learning',
                'learning-selection-interaction/interaction-evolved-learned-cooperation/two-timescale-simulations/simulations-model-2-q-learning',
                'learning-selection-interaction/interaction-evolved-learned-cooperation/two-timescale-simulations/simulations-model-3-extended',
                'learning-selection-interaction/interaction-evolved-learned-cooperation/two-timescale-simulations/simulations-experiment-network-diversity',
                'learning-selection-interaction/interaction-evolved-learned-cooperation/two-timescale-simulations/simulations-appendices',
              ],
            },
            {
              type: 'category',
              label: 'Foundational Replications',
              collapsed: true,
              items: [
                'learning-selection-interaction/interaction-evolved-learned-cooperation/foundational-theory/ackley-littman-1991',
                'learning-selection-interaction/interaction-evolved-learned-cooperation/foundational-theory/ackley-littman-1994',
                'learning-selection-interaction/interaction-evolved-learned-cooperation/foundational-theory/hinton-nowlan-1987',
                'learning-selection-interaction/interaction-evolved-learned-cooperation/foundational-theory/prosser-2022',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Research Log & Archive',
      collapsed: false,
      items: [
        'learning-selection-interaction/interaction-evolved-learned-cooperation/research-log/darwin-baldwin-trial-log',
        'learning-selection-interaction/interaction-evolved-learned-cooperation/research-log/related-research-predpreygrass',
        'learning-selection-interaction/interaction-evolved-learned-cooperation/research-log/mindmap',
        'archive/archive-overview',
      ],
    },
  ],
};
