export default {
  tutorialSidebar: [
    'the-nature-and-nurture-of-cooperation-and-competition',
    {
      type: 'category',
      label: 'Core Argument',
      collapsed: false,
      items: [
        'nature-nurture-human-behavior',
        {
          type: 'category',
          label: 'Cooperation in Perspective',
          link: { type: 'doc', id: 'cooperation-in-perspective/cooperation-in-perspective' },
          collapsed: false,
          items: [
            'cooperation-in-perspective/what-is-cooperation/what-is-cooperation',
            'cooperation-in-perspective/what-is-adversarial-behavior/what-is-adversarial-behavior',
            'cooperation-in-perspective/history-of-human-cooperation-and-competition/history-of-human-cooperation-and-competition',
          ],
        },
        'evolved-cooperation/evolved-cooperation',
        'learned-cooperation/learned-cooperation',
        'learning-selection-interaction/interaction-evolved-learned-cooperation/interaction-evolved-learned-cooperation',
        'learning-selection-interaction/interaction-evolved-learned-cooperation/foundational-theory/baldwin-effect',
      ],
    },
    {
      type: 'category',
      label: 'Evolved Cooperation Models',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'evolved-cooperation' },
      ],
    },
    {
      type: 'category',
      label: 'Learned Cooperation Models',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: "Prisoner's Dilemma",
          link: { type: 'doc', id: 'learned-cooperation/prisoners-dilemma/prisoners-dilemma' },
          collapsed: false,
          items: [],
        },
        {
          type: 'category',
          label: "Repeated Prisoner's Dilemma",
          link: { type: 'doc', id: 'learned-cooperation/repeated-prisoners-dilemma/repeated-prisoners-dilemma' },
          collapsed: false,
          items: [
            'learned-cooperation/repeated-prisoners-dilemma/ppo-study',
          ],
        },
      ],
    },
    { type: 'autogenerated', dirName: 'learning-selection-interaction' },
  ],
};
